---
- name: Install package
  yum:
    name: "{{ package_name }}"
    state: latest

- name: Check whether package is installed
  shell: rpm -qi "{{ package_name }}"
  register: output

- debug: msg="{{ output.stdout }}"

- name: copy index file
  copy:
    src: /public/index.html
    dest: /var/www/html
    
- name: copy image file
  copy:
    src: /public/GIF.pnh
    dest: /var/www/html

- name: Start and enable service
  service:
    name: "{{ service_name }}"
    state: started
    enabled: yes
